// <auto-generated />
using System;
using Juan_Maria_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Juan_Maria_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250715110642_Primera migracion")]
    partial class Primeramigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Juan_Maria_AP1_P2.Models.Entradas", b =>
                {
                    b.Property<int>("EntradasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntradasId"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntradasId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Juan_Maria_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("DetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetallesId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("EntradasId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("DetallesId");

                    b.HasIndex("EntradasId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Juan_Maria_AP1_P2.Models.Producto", b =>
                {
                    b.Property<int>("ProductosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductosId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.HasKey("ProductosId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductosId = 1,
                            Descripcion = "Mani",
                            Peso = 12.0
                        },
                        new
                        {
                            ProductosId = 2,
                            Descripcion = "Almendra",
                            Peso = 17.0
                        },
                        new
                        {
                            ProductosId = 3,
                            Descripcion = "Pistacho",
                            Peso = 3.0
                        });
                });

            modelBuilder.Entity("Juan_Maria_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.HasOne("Juan_Maria_AP1_P2.Models.Entradas", null)
                        .WithMany("EntradasDetalle")
                        .HasForeignKey("EntradasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Juan_Maria_AP1_P2.Models.Producto", "Producto")
                        .WithMany("EntradasDetalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Juan_Maria_AP1_P2.Models.Entradas", b =>
                {
                    b.Navigation("EntradasDetalle");
                });

            modelBuilder.Entity("Juan_Maria_AP1_P2.Models.Producto", b =>
                {
                    b.Navigation("EntradasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
